WORKOUTS = {
    "fullBody": [
        {"name": 'Warm-up', "reps": '5-10 minutes of light cardio',
            "video": "https://www.youtube.com/watch?v=c0VxUFHdYzs"},
        {"name": 'Squats', "reps": '3 sets of 10-12 reps',
            "video": "https://www.youtube.com/watch?v=mGvzVjuY8SY"},
        {"name": 'Push-ups', "reps": '3 sets of as many reps as possible',
            "video": "https://www.youtube.com/watch?v=3RuPQ9VW_x8"},
        {"name": 'Lunges', "reps": '3 sets of 10-12 reps per leg',
            "video": "https://www.youtube.com/watch?v=_ggxoUsCx7A"},
        {"name": 'Crunches', "reps": '3 sets of 15-20 reps',
            "video": "https://www.youtube.com/watch?v=cgsvJMZ04BU"},
        {"name": 'Plank', "reps": '30-60 seconds',
            "video": "https://www.youtube.com/watch?v=d4dFAF6HWa0"},
        {"name": 'Cool-down', "reps": '5-10 minutes of stretching',
            "video": "https://www.youtube.com/watch?v=SbURodJWeMM"},
    ],
    "upperBody": [
        {"name": 'Warm-up', "reps": '5-10 minutes of light cardio',
            "video": "https://www.youtube.com/watch?v=mf6CZ5_7dfc"},
        {"name": 'Bench press', "reps": '3 sets of 8-10 reps',
            "video": "https://www.youtube.com/watch?v=lNvRXBBud4c"},
        {"name": 'Overhead press', "reps": '3 sets of 8-10 reps',
            "video": "https://www.youtube.com/watch?v=JLfmB3PdqIs"},
        {"name": 'Pull-ups', "reps": '3 sets of as many reps as possible',
            "video": "https://www.youtube.com/watch?v=vHQErDi1ufU"},
        {"name": 'Rows', "reps": '3 sets of 8-10 reps',
            "video": "https://www.youtube.com/watch?v=Du5oIfDeayg"},
        {"name": 'Triceps extensions', "reps": '3 sets of 12-15 reps',
            "video": "https://www.youtube.com/watch?v=_gsUck-7M74"},
        {"name": 'Biceps curls', "reps": '3 sets of 12-15 reps',
            "video": "https://www.youtube.com/watch?v=Nkl8WnH6tDU"},
        {"name": 'Cool-down', "reps": '5-10 minutes of stretching',
            "video": "https://www.youtube.com/watch?v=jENl5e4-ZaI"},
    ],
    "lowerBody": [
        {"name": 'Warm-up', "reps": '5-10 minutes of light cardio',
            "video": "https://www.youtube.com/watch?v=YAPloaFQF0E"},
        {"name": 'Squats', "reps": '3 sets of 10-12 reps',
            "video": "https://www.youtube.com/watch?v=-c3_Prg2SEc"},
        {"name": 'Deadlifts', "reps": '3 sets of 5-8 reps',
            "video": "https://www.youtube.com/watch?v=R0FxMguetIw"},
        {"name": 'Lunges', "reps": '3 sets of 10-12 reps per leg',
            "video": "https://www.youtube.com/watch?v=uVwNVEQS_uo"},
        {"name": 'Leg press', "reps": '3 sets of 12-15 reps',
            "video": "https://www.youtube.com/watch?v=zZ8tWnE8kzQ"},
        {"name": 'Hamstring curls', "reps": '3 sets of 12-15 reps',
            "video": "https://www.youtube.com/watch?v=MRAcmrGnwvE"},
        {"name": 'Calf raises', "reps": '3 sets of 15-20 reps',
            "video": "https://www.youtube.com/watch?v=eWRJrRYVe0k"},
        {"name": 'Cool-down', "reps": '5-10 minutes of stretching',
            "video": "https://www.youtube.com/watch?v=SbURodJWeMM"},
    ],
    "cardio": [
        {"name": 'Warm-up', "reps": '5-10 minutes of light cardio',
            "video": "https://www.youtube.com/watch?v=sF9C-wqtWzc"},
        {
            "name": 'Sprints', "video": "https://www.youtube.com/watch?v=Kb_teIwloC0",
            "reps": '3 sets of 30 seconds of sprinting, followed by 90 seconds of rest',
        },
        {
            "name": 'Interval training', "video": "https://www.youtube.com/watch?v=M0uO8X3_tEA",
            "reps": '30 minutes of alternating between 30 seconds of high-intensity exercise and 1 minute of low-intensity exercise',
        },
        {
            "name": 'Steady-state cardio', "video": "https://www.youtube.com/watch?v=ImI63BUUPwU",
            "reps": '30-60 minutes of moderate-intensity exercise, such as running, biking, or swimming',
        },
        {"name": 'Cool-down', "reps": '5-10 minutes of light cardio',
            "video": "https://www.youtube.com/watch?v=SbURodJWeMM"},
    ],
}

NUTRITION_DATA = [
    {
        "time": 'Breakfast',
        "meals": [
            {"name": 'Oatmeal, Greek yogurt, and fruit',
                "image_url": "assets/images/diet/Oatmeal_Greekyogurt_fruit.jpg"},
            {"name": 'Smoothie with spinach, banana, berries, and almond milk',
                "image_url": "assets/images/diet/Smoothie_spinach_banana_berries_almond_milk.jpg"},
            {"name": 'Whole grain toast with avocado, poached egg, and cherry tomatoes',
                "image_url": "assets/images/diet/Wholegraintoastwithavocado_poachedegg_cherry_tomatoes.jpg"},
            {"name": 'Overnight chia pudding with almond milk, honey, and mixed berries',
                "image_url": "assets/images/diet/Overnightchiapudding_almondmilkhoney_mixed_berries.jpg"},
        ],
    },
    {
        "time": 'Lunch',
        "meals": [
            {"name": 'Grilled chicken salad with vinaigrette',
                "image_url": "assets/images/diet/Grilled_chicken_salad_with_vinaigrette.jpg"},
            {"name": 'Quinoa, black bean, and avocado salad',
                "image_url": "assets/images/diet/Quinoa_black_bean_and_avocado_salad.jpeg"},
            {"name": 'Whole grain wrap with hummus, turkey, and mixed vegetables',
                "image_url": "assets/images/diet/Whole_grain_wrap_with_hummus_turkey_and_mixed_vegetables.jpeg"},
            {"name": 'Brown rice sushi with salmon, avocado, and cucumber',
                "image_url": "assets/images/diet/Brown_rice_sushi_with_salmon_avocado_and_cucumber.jpeg"},
        ],
    },
    {
        "time": 'Dinner',
        "meals": [
            {"name": 'Salmon, quinoa, and steamed vegetables',
                "image_url": "assets/images/diet/Salmon_quinoa_and_steamend_vegetables.jpeg"},
            {"name": 'Stir-fried tofu with mixed vegetables and brown rice',
                "image_url": "assets/images/diet/Stir-fried_tofu_with_mixed_vegetables_and_brown_rice.jpg"},
            {"name": 'Grilled lean steak with baked sweet potato and steamed green beans',
                "image_url": "assets/images/diet/Grilled_lean_steak_with_baked_sweet_potato_and_steamed_green_beans.jpeg"},
            {"name": 'Baked chicken with roasted Brussels sprouts and a side of whole grain couscous',
                "image_url": "assets/images/diet/Baked_chicken_with_roasted_Brussels_sprouts_and_a_side_of_whole_grain_couscous.jpg"},
        ],
    },
    {
        "time": 'Snacks',
        "meals": [
            {"name": 'Sliced apple with almond butter',
                "image_url": "assets/images/diet/Sliced_apple_with_almond_butter.jpg"},
            {"name": 'Carrots and cucumber with hummus',
                "image_url": "assets/images/diet/Carrots_and_cucumber_with_hummus.jpg"},
            {"name": 'Mixed nuts and dried fruit',
                "image_url": "assets/images/diet/Mixed_nuts_and_dried_fruit.jpg"},
            {"name": 'Greek yogurt with honey and walnuts',
                "image_url": "assets/images/diet/Greek_yogurt_with_honey_and_walnuts.jpg"},
        ],
    },
]

ARTICLES = [
    {
        "title": "10 Tips to Improve Your Workout",
        "summary": "Learn how to make the most out of your workouts with these 10 essential tips.",
        "image_url": "https://www.yeoandyeo.com/wp-content/uploads/AdobeStock_298320299-1067x800.jpeg",
        "url": "https://www.hsph.harvard.edu/nutritionsource/2013/11/04/making-exercise-a-daily-habit-10-tips/",
    },
    {
        "title": "The Benefits of High-Intensity Interval Training",
        "summary": "Discover the science-backed benefits of HIIT and why it's so effective.",
        "image_url": "https://static.scientificamerican.com/sciam/cache/file/F7AC4011-A227-4E87-B4C5CA373BE2D382_source.jpg?w=590&h=800&7CCE65EF-D3AE-4216-80148F994817305E",
        "url": "https://www.healthline.com/nutrition/benefits-of-hiit",
    },
    {
        "title": "5 Nutrition Tips for Better Performance",
        "summary": "Fuel your body the right way with these helpful nutrition tips for athletes.",
        "image_url": "https://www.hsph.harvard.edu/nutritionsource/wp-content/uploads/sites/30/2012/09/vegetables-and-fruits-farmers-market.jpg",
        "url": "https://www.mayoclinichealthsystem.org/hometown-health/speaking-of-health/5-nutrition-tips-to-maximize-your-workouts",
    },
]
